# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/wlessley/Personal/bug-free-goggles

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/wlessley/Personal/bug-free-goggles

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/wlessley/Personal/bug-free-goggles/CMakeFiles /Users/wlessley/Personal/bug-free-goggles//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/wlessley/Personal/bug-free-goggles/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named tutorial

# Build rule for target.
tutorial: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tutorial
.PHONY : tutorial

# fast build rule for target.
tutorial/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tutorial.dir/build.make CMakeFiles/tutorial.dir/build
.PHONY : tutorial/fast

#=============================================================================
# Target rules for targets named math

# Build rule for target.
math: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 math
.PHONY : math

# fast build rule for target.
math/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/math.dir/build.make CMakeFiles/math.dir/build
.PHONY : math/fast

#=============================================================================
# Target rules for targets named sandbox

# Build rule for target.
sandbox: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sandbox
.PHONY : sandbox

# fast build rule for target.
sandbox/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sandbox.dir/build.make CMakeFiles/sandbox.dir/build
.PHONY : sandbox/fast

math_lib/main.o: math_lib/main.cpp.o
.PHONY : math_lib/main.o

# target to build an object file
math_lib/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/math.dir/build.make CMakeFiles/math.dir/math_lib/main.cpp.o
.PHONY : math_lib/main.cpp.o

math_lib/main.i: math_lib/main.cpp.i
.PHONY : math_lib/main.i

# target to preprocess a source file
math_lib/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/math.dir/build.make CMakeFiles/math.dir/math_lib/main.cpp.i
.PHONY : math_lib/main.cpp.i

math_lib/main.s: math_lib/main.cpp.s
.PHONY : math_lib/main.s

# target to generate assembly for a file
math_lib/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/math.dir/build.make CMakeFiles/math.dir/math_lib/main.cpp.s
.PHONY : math_lib/main.cpp.s

math_lib/matrix.o: math_lib/matrix.cpp.o
.PHONY : math_lib/matrix.o

# target to build an object file
math_lib/matrix.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/math.dir/build.make CMakeFiles/math.dir/math_lib/matrix.cpp.o
.PHONY : math_lib/matrix.cpp.o

math_lib/matrix.i: math_lib/matrix.cpp.i
.PHONY : math_lib/matrix.i

# target to preprocess a source file
math_lib/matrix.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/math.dir/build.make CMakeFiles/math.dir/math_lib/matrix.cpp.i
.PHONY : math_lib/matrix.cpp.i

math_lib/matrix.s: math_lib/matrix.cpp.s
.PHONY : math_lib/matrix.s

# target to generate assembly for a file
math_lib/matrix.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/math.dir/build.make CMakeFiles/math.dir/math_lib/matrix.cpp.s
.PHONY : math_lib/matrix.cpp.s

math_lib/vector_methods.o: math_lib/vector_methods.cpp.o
.PHONY : math_lib/vector_methods.o

# target to build an object file
math_lib/vector_methods.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/math.dir/build.make CMakeFiles/math.dir/math_lib/vector_methods.cpp.o
.PHONY : math_lib/vector_methods.cpp.o

math_lib/vector_methods.i: math_lib/vector_methods.cpp.i
.PHONY : math_lib/vector_methods.i

# target to preprocess a source file
math_lib/vector_methods.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/math.dir/build.make CMakeFiles/math.dir/math_lib/vector_methods.cpp.i
.PHONY : math_lib/vector_methods.cpp.i

math_lib/vector_methods.s: math_lib/vector_methods.cpp.s
.PHONY : math_lib/vector_methods.s

# target to generate assembly for a file
math_lib/vector_methods.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/math.dir/build.make CMakeFiles/math.dir/math_lib/vector_methods.cpp.s
.PHONY : math_lib/vector_methods.cpp.s

sandbox_lib/eagerness.o: sandbox_lib/eagerness.cpp.o
.PHONY : sandbox_lib/eagerness.o

# target to build an object file
sandbox_lib/eagerness.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sandbox.dir/build.make CMakeFiles/sandbox.dir/sandbox_lib/eagerness.cpp.o
.PHONY : sandbox_lib/eagerness.cpp.o

sandbox_lib/eagerness.i: sandbox_lib/eagerness.cpp.i
.PHONY : sandbox_lib/eagerness.i

# target to preprocess a source file
sandbox_lib/eagerness.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sandbox.dir/build.make CMakeFiles/sandbox.dir/sandbox_lib/eagerness.cpp.i
.PHONY : sandbox_lib/eagerness.cpp.i

sandbox_lib/eagerness.s: sandbox_lib/eagerness.cpp.s
.PHONY : sandbox_lib/eagerness.s

# target to generate assembly for a file
sandbox_lib/eagerness.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sandbox.dir/build.make CMakeFiles/sandbox.dir/sandbox_lib/eagerness.cpp.s
.PHONY : sandbox_lib/eagerness.cpp.s

sandbox_lib/sandbox.o: sandbox_lib/sandbox.cpp.o
.PHONY : sandbox_lib/sandbox.o

# target to build an object file
sandbox_lib/sandbox.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sandbox.dir/build.make CMakeFiles/sandbox.dir/sandbox_lib/sandbox.cpp.o
.PHONY : sandbox_lib/sandbox.cpp.o

sandbox_lib/sandbox.i: sandbox_lib/sandbox.cpp.i
.PHONY : sandbox_lib/sandbox.i

# target to preprocess a source file
sandbox_lib/sandbox.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sandbox.dir/build.make CMakeFiles/sandbox.dir/sandbox_lib/sandbox.cpp.i
.PHONY : sandbox_lib/sandbox.cpp.i

sandbox_lib/sandbox.s: sandbox_lib/sandbox.cpp.s
.PHONY : sandbox_lib/sandbox.s

# target to generate assembly for a file
sandbox_lib/sandbox.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sandbox.dir/build.make CMakeFiles/sandbox.dir/sandbox_lib/sandbox.cpp.s
.PHONY : sandbox_lib/sandbox.cpp.s

tutorial.o: tutorial.cxx.o
.PHONY : tutorial.o

# target to build an object file
tutorial.cxx.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tutorial.dir/build.make CMakeFiles/tutorial.dir/tutorial.cxx.o
.PHONY : tutorial.cxx.o

tutorial.i: tutorial.cxx.i
.PHONY : tutorial.i

# target to preprocess a source file
tutorial.cxx.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tutorial.dir/build.make CMakeFiles/tutorial.dir/tutorial.cxx.i
.PHONY : tutorial.cxx.i

tutorial.s: tutorial.cxx.s
.PHONY : tutorial.s

# target to generate assembly for a file
tutorial.cxx.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tutorial.dir/build.make CMakeFiles/tutorial.dir/tutorial.cxx.s
.PHONY : tutorial.cxx.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... math"
	@echo "... sandbox"
	@echo "... tutorial"
	@echo "... math_lib/main.o"
	@echo "... math_lib/main.i"
	@echo "... math_lib/main.s"
	@echo "... math_lib/matrix.o"
	@echo "... math_lib/matrix.i"
	@echo "... math_lib/matrix.s"
	@echo "... math_lib/vector_methods.o"
	@echo "... math_lib/vector_methods.i"
	@echo "... math_lib/vector_methods.s"
	@echo "... sandbox_lib/eagerness.o"
	@echo "... sandbox_lib/eagerness.i"
	@echo "... sandbox_lib/eagerness.s"
	@echo "... sandbox_lib/sandbox.o"
	@echo "... sandbox_lib/sandbox.i"
	@echo "... sandbox_lib/sandbox.s"
	@echo "... tutorial.o"
	@echo "... tutorial.i"
	@echo "... tutorial.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

