version: '3'

tasks:
  build:
    cmds:
      - clang++ -std=c++11 -stdlib=libc++ -lglfw3 -framework CoreVideo -framework OpenGL -framework IOKit -framework Cocoa -framework Carbon ./example.cpp

  run:
    cmds:
     - ./a.out