version: '3'

tasks:

  build:
    cmds:
      # compile main
      - clang++ -std=c++11 -stdlib=libc++ -I./include -I./include/glad/include -lglfw3 -ldl -framework CoreVideo -framework OpenGL -framework IOKit -framework Cocoa -framework Carbon ./main.cpp ./gl.o -o main
  run:
    cmds:
     - ./main

  start:
    cmds:
      - task build
      - task run

  build:example:
    cmds:
      - clang++ -std=c++11 -stdlib=libc++ -lglfw3 -framework CoreVideo -framework OpenGL -framework IOKit -framework Cocoa -framework Carbon ./example.cpp

  run:example:
    cmds:
     - ./a.out

  build:glad:
    cmds:
      # compile GLAD library
      - gcc -c include/glad/src/glad.c -I./include/glad/include -lglfw3 -ldl -o gl.o

  build:test:
    cmds:
      - clang++ -std=c++11 -stdlib=libc++ -I./include/glad/include -I./include -lglfw3 -ldl -framework CoreVideo -framework OpenGL -framework IOKit -framework Cocoa -framework Carbon ./test.cpp ./include/glad/src/glad.c -o test

  run:test:
    cmds:
      - ./test

  start:test:
    cmds:
      - task build:test
      - task run:test
